/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoPmRouteImport } from './routes/co-pm'
import { Route as IndexRouteImport } from './routes/index'

const CoPmRoute = CoPmRouteImport.update({
  id: '/co-pm',
  path: '/co-pm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/co-pm': typeof CoPmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/co-pm': typeof CoPmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/co-pm': typeof CoPmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/co-pm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/co-pm'
  id: '__root__' | '/' | '/co-pm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoPmRoute: typeof CoPmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/co-pm': {
      id: '/co-pm'
      path: '/co-pm'
      fullPath: '/co-pm'
      preLoaderRoute: typeof CoPmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoPmRoute: CoPmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
